export interface CandidateFiltersDto {
    categoryId?: string;
    search?: string;
    experienceYears?: number;
    religion?: string;
    gender?: string;
    minAge?: number;
    maxAge?: number;
    medicalStatus?: string;
    cocStatus?: string;
    isAvailable?: boolean;
    page?: number;
    limit?: number;
}

export interface VacancyFiltersDto {
    categoryId?: string;
    search?: string;
    country?: string;
    salaryMin?: number;
    status?: string;
    page?: number;
    limit?: number;
}

export interface CandidateDto {
    id: string;
    agencyId: string;
    categoryId: string;
    firstName: string;
    middleName?: string;
    lastName: string;
    fullNameAmharic?: string;
    dateOfBirth?: string;
    age?: number;
    gender?: string;
    nationality?: string;
    religion?: string;
    maritalStatus?: string;
    numberOfChildren?: number;
    heightCm?: number;
    weightKg?: number;
    complexion?: string;
    phone?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
    emergencyContactRelation?: string;
    currentCountry?: string;
    city?: string;
    originRegion?: string;
    summary?: string;
    educationLevel?: string;
    yearsOfExperience?: number;
    experienceYears?: number;
    hasOverseasExperience?: boolean;
    overseasDetails?: string;
    localExperienceDetails?: string;
    appliedPosition?: string;
    passportNumber?: string;
    passportIssueDate?: string;
    passportExpiryDate?: string;
    passportPlaceOfIssue?: string;
    nationalIdNumber?: string;
    cocStatus?: string;
    cocIssueDate?: string;
    policeClearanceStatus?: string;
    medicalStatus?: string;
    medicalClearanceDate?: string;
    medicalExpiryDate?: string;
    visaStatus?: string;
    expectedSalary?: number;
    expectedSalaryCurrency?: string;
    contractPeriodYears?: number;
    photoUrl?: string;
    fullBodyPhotoUrl?: string;
    videoUrl?: string;
    videoThumbnail?: string;
    passportCopyUrl?: string;
    medicalCertUrl?: string;
    cocCertUrl?: string;
    isFeatured?: boolean;
    isAvailable: boolean;
    isPublished: boolean;
    skills?: string[];
    languages?: string[];
    category?: { id: string; name: string };
    agency?: { id: string; name: string; logoUrl?: string };
}

export interface JobVacancyDto {
    id: string;
    agencyId: string;
    categoryId: string;
    title: string;
    jobCode?: string;
    description: string;
    requirements?: string[];
    country?: string;
    city?: string;
    targetRegion?: string;
    employerType?: string;
    employerName?: string;
    showEmployerName?: boolean;
    foreignAgencyPartner?: string;
    salaryMin?: number;
    salaryMax?: number;
    currency?: string;
    salaryCurrency?: string;
    overtimeTerms?: string;
    placementFeeTerms?: string;
    contractPeriodYears?: number;
    probationPeriodMonths?: number;
    workingHoursPerDay?: number;
    workingDaysPerWeek?: number;
    offDaysPerMonth?: number;
    visaSponsorship?: boolean;
    accommodationProvided?: boolean;
    mealsProvided?: boolean;
    transportationProvided?: boolean;
    healthInsurance?: boolean;
    flightTicketProvided?: boolean;
    annualLeaveDays?: number;
    genderPreference?: string;
    religionPreference?: string;
    ageMin?: number;
    ageMax?: number;
    experienceRequired?: number;
    overseasExpRequired?: boolean;
    educationLevelRequired?: string;
    requiredSkills?: string[];
    requiredLanguages?: string[];
    requiredCertificates?: string[];
    vacanciesCount?: number;
    applicationDeadline?: string;
    status: string;
    category?: { id: string; name: string };
    agency?: { id: string; name: string; logoUrl?: string };
}

